### ISSUE TITLE
UI Design: Change Nav buttons to Icons

### ISSUE THREAD

**Issue by carsonSgit** [AlejandroCadena-JAC/GymPlanner#22]
**Task Description**
Swap the Navigation buttons to use a Navigation bar with Icons to navigate through pages.

**Steps**
-  [x] Create Nav Bar for Nav buttons
-  [x] Add Navigation into Nav bar
-  [x] Navigation uses Icons

**Technical effort (LOE)**
4/10

**Additional context**
Add any other context about the task here.
