### ISSUE TITLE
Create a Landing Screen using Coroutines

### ISSUE THREAD

**Issue by carsonSgit** [AlejandroCadena-JAC/GymPlanner#30]
**Task Description**
Build a Landing Screen that uses the coroutines in Composition. Use that landing screen on the Main page for when we boot the application. 

**Steps**
List all steps that are required to complete the task

- [x] Create Landing Screen file
- [x] Create Visual landing screen within file
- [x] Implement coroutines within Landing screen
- [x] Implement Landing Screen in Main launch

**Technical effort (LOE)**
4/10
