### ISSUE TITLE
Notes uses Datastore

### ISSUE THREAD

**Issue by carsonSgit** [AlejandroCadena-JAC/GymPlanner#36]
**Task Description**
Every new note submission gets stored in Data Store.

**Steps**
List all steps that are required to complete the task

- [ ] Have Data store
- [ ] Modify data input
- [ ] Add new items added by user to data store

**Technical effort (LOE)**
4/10
