### ISSUE TITLE
Calendar accesses Data Store

### ISSUE THREAD

**Issue by carsonSgit** [AlejandroCadena-JAC/GymPlanner#37]
**Task Description**
The calendar should display  firestore data for that day.

**Steps**
List all steps that are required to complete the task

- [ ] Calendar on date click opens a Composable
- [ ] Composable reads from  Firestore 
- [ ] Composable renders the Firestore data
- [ ] Calendar dates filter Firestore data

**Technical effort (LOE)**
5/10
