### ISSUE TITLE
Modify navbar to use Icons

### ISSUE THREAD

**Issue by carsonSgit** [AlejandroCadena-JAC/GymPlanner#44]
**Task Description**
Currently, we have text for our navbar options. Not only is this not very appealing, but it also does not work well with several navbar items. Change the display to use icons.

**Steps**
List all steps that are required to complete the task

- [x] Add Icon to all navbar items
- [x] Remove text from navbar display
- [x] Use navbar icon in text display
- [x] Tweak with display variables

**Technical effort (LOE)**
4/10
