### ISSUE TITLE
Fix UI

### ISSUE THREAD

**Issue by carsonSgit** [AlejandroCadena-JAC/GymPlanner#45]
**Task Description**
We are using the default Android UI. Make a theme that works in Light mode & one for Dark mode that is visually appealing and functions properly.

**Steps**
List all steps that are required to complete the task

- [x] Fix dynamic theming
- [x] Light & Dark Mode colour themes
- [x] Remove unnecessary surfaces
- [x] Remove "Workout Tracker" header

**Technical effort (LOE)**
6/10
