### ISSUE TITLE
Remove Exercise List

### ISSUE THREAD

**Issue by carsonSgit** [AlejandroCadena-JAC/GymPlanner#73]
**Task Description**
Exercise List does not fit into the scope of our final project and should be removed.

**Steps**
List all steps that are required to complete the task

- [x] Delete the ExerciseList.kt
- [x] Delete the exerciselist package
- [x] Delete Navbar object of ExerciseList
- [x] Remove Navbar call of ExerciseList

**Technical effort (LOE)**
1/10

**Comment by carsonSgit** [comment]
Donezo
